# Generated by Django 4.2.11 on 2024-04-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Groceries', 'Groceries'), ('Entertainment', 'Entertainment'), ('Transportation', 'Transportation')], max_length=100)),
                ('account', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
